# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class Test4TrackEarnings():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_4TrackEarnings(self):
    self.driver.get("http://localhost:3000/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.NAME, "name").click()
    self.driver.find_element(By.NAME, "name").send_keys("Gajendra.Patel")
    self.driver.find_element(By.NAME, "password").click()
    self.driver.find_element(By.NAME, "password").send_keys("test")
    self.driver.find_element(By.NAME, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.CSS_SELECTOR, ".setting").click()
    self.driver.find_element(By.CSS_SELECTOR, ".settings_account-inner:nth-child(7) > .settings__left--account-content").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > td:nth-child(4)").click()
    self.driver.find_element(By.LINK_TEXT, "Back to Main Page").click()
    self.driver.find_element(By.LINK_TEXT, "Track Earnings").click()
    self.driver.find_element(By.CSS_SELECTOR, ".total-row > td:nth-child(1)").click()
    self.driver.find_element(By.LINK_TEXT, "Back to Main Page").click()
    self.driver.find_element(By.CSS_SELECTOR, ".setting__right--btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".btn-danger-outline").click()
  
